### ISSUE TITLE
PyUnicodeUCS4_DecodeUTF8 error

### ISSUE THREAD

**Issue by kokkytos** [ssec/polar2grid#152]
I'm getting the following  polar2grid ImportError:
```
Traceback (most recent call last):

  File "/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/runpy.py", line 176, in _run_module_as_main
    "__main__", fname, loader, pkg_name)

  File "/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/runpy.py", line 74, in _run_code
    exec code in run_globals

  File "/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/polar2grid/glue.py", line 47, in <module>
    from polar2grid.readers import ReaderWrapper, convert_satpy_to_p2g_swath, convert_satpy_to_p2g_gridded

  File "/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/polar2grid/readers/__init__.py", line 46, in <module>
    from pyresample.geometry import AreaDefinition

  File "/usr/local/lib/python2.7/dist-packages/pyresample/__init__.py", line 27, in <module>
    from pyresample import image  # noqa

  File "/usr/local/lib/python2.7/dist-packages/pyresample/image.py", line 24, in <module>
    from pyresample import geometry, grid, kd_tree, bilinear

  File "/usr/local/lib/python2.7/dist-packages/pyresample/kd_tree.py", line 29, in <module>
    from pykdtree.kdtree import KDTree`

ImportError: /usr/local/lib/python2.7/dist-packages/pykdtree/kdtree.so: undefined symbol: PyUnicodeUCS4_DecodeUTF
```

**Comment by djhoese** [comment]
Do you have the `LD_LIBRARY_PATH` or `PYTHONPATH` environment variable set? You can see from the paths in the error message that Polar2Grid's python environment is being pointed to packages you have installed in `/usr/local`. All P2G releases are self-contained and do not need outside libraries and if built correctly (by me) they shouldn't be pointing outside of P2G.

What command are you using to produce this error?

**Comment by kokkytos** [comment]
I run:
` polar2grid.sh  viirs_sdr gtiff -f ./001/*.h5`

LD_LIBRARY_PATH and PYTHONPATH are not in my env.

**Comment by djhoese** [comment]
What do you get when you run:

```bash
source /home/leonidas/Downloads/polar2grid_v_2_2_1/bin/polar2grid_env.sh
which python
echo $PYTHON_PATH
python -c "import sys; print(sys.path)"
```

**Comment by kokkytos** [comment]
```
leonidas@gisbox:~$ source /home/leonidas/Downloads/polar2grid_v_2_2_1/bin/polar2grid_env.sh
leonidas@gisbox:~$ which python
/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/bin/python
leonidas@gisbox:~$ echo $PYTHON_PATH

leonidas@gisbox:~$ python -c "import sys; print(sys.path)"
['', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python27.zip', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/plat-linux2', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/lib-tk', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/lib-old', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/lib-dynload', '/home/leonidas/.local/lib/python2.7/site-packages', '/home/leonidas/.local/lib/python2.7/site-packages/mpop-1.5.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/setuptools-28.8.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/setuptools_scm-1.15.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pyproj-1.9.5.1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/Cython-0.25.1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/six-1.10.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/h5py-2.6.0-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/numexpr-2.6.1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/tables-3.3.0-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/scipy-0.18.1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pyparsing-2.1.10-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/python_dateutil-2.6.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/backports_abc-0.4-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/certifi-2016.9.26-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pbr-1.10.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/funcsigs-1.0.2-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pytz-2016.7-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/functools32-3.2.3.post2-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/python_hdf4-0.9-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/Shapely-1.6a1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/Bottleneck-1.2.0-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/blosc-1.4.4-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/Pillow-3.4.2-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/configobj-5.0.6-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/trollsift-0.1.1-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/trollimage-0.4.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/PyYAML-3.12-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pyorbital-1.0.1-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pyshp-1.2.3-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pycoast-0.7.0a0-py2.7.egg']
leonidas@gisbox:~$ 

```

**Comment by djhoese** [comment]
I'm sorry could you do `echo $PYTHONPATH`. I typed it wrong before.

**Comment by kokkytos** [comment]
echo $PYTHONPATH returns nothing...

```
leonidas@gisbox:~$ source /home/leonidas/Downloads/polar2grid_v_2_2_1/bin/polar2grid_env.sh
leonidas@gisbox:~$ which python
/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/bin/python
leonidas@gisbox:~$ echo $PYTHONPATH

leonidas@gisbox:~$ python -c "import sys; print(sys.path)"
['', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python27.zip', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/plat-linux2', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/lib-tk', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/lib-old', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/lib-dynload', '/home/leonidas/.local/lib/python2.7/site-packages', '/home/leonidas/.local/lib/python2.7/site-packages/mpop-1.5.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/setuptools-28.8.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/setuptools_scm-1.15.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pyproj-1.9.5.1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/Cython-0.25.1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/six-1.10.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/h5py-2.6.0-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/numexpr-2.6.1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/tables-3.3.0-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/scipy-0.18.1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pyparsing-2.1.10-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/python_dateutil-2.6.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/backports_abc-0.4-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/certifi-2016.9.26-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pbr-1.10.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/funcsigs-1.0.2-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pytz-2016.7-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/functools32-3.2.3.post2-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/python_hdf4-0.9-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/Shapely-1.6a1-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/Bottleneck-1.2.0-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/blosc-1.4.4-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/Pillow-3.4.2-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/configobj-5.0.6-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/trollsift-0.1.1-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/trollimage-0.4.0-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/PyYAML-3.12-py2.7-linux-x86_64.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pyorbital-1.0.1-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pyshp-1.2.3-py2.7.egg', '/home/leonidas/Downloads/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/pycoast-0.7.0a0-py2.7.egg']

```

**Comment by djhoese** [comment]
Thank you. And are you on a RHEL/CentOS machine or Ubuntu or some other linux distribution?

I will look in to this.

**Comment by kokkytos** [comment]
Debian 9.5
Thank you!

**Comment by djhoese** [comment]
Try this after the `source` command from before:

```bash
python -s -m polar2grid.glue -vv viirs_sdr gtiff -f ./001/*.h
```

If this does not work could you provide me with the output of
`ls -1 '/home/leonidas/.local/lib/python2.7/site-packages'`

NOTE: Debian is not one of our supported platforms so there is no guarantee that Polar2Grid will work on your system, but with a little bit of work it may be possible.

**Comment by 7yl4r** [comment]
>     from pykdtree.kdtree import KDTree`

What's up with that trailing backtick? I don't see it in the [pyresample src](https://github.com/pytroll/pyresample/blob/master/pyresample/kd_tree.py#L29).

**Comment by djhoese** [comment]
@7yl4r That's a good question, but the main issue is that packages from `/usr/local` are being used at all. Polar2Grid is set up to not need anything outside of its own directory and tries hard to keep things pointing to the right places. We test explicitly on CentOS systems and have had users have success on some Ubuntu systems and those never seemed to include some of the paths @kokkytos is seeing in `sys.path`.

**Comment by kokkytos** [comment]
` python -s -m polar2grid.glue -vv viirs_sdr gtiff -f ./001/*.h`
returns
`/usr/bin/python: No module named polar2grid
`

 `ls -1 '/home/leonidas/.local/lib/python2.7/site-packages'`

returns 
```
apiclient
backports
backports_abc-0.5.dist-info
backports_abc.py
backports_abc.pyc
backports.shutil_get_terminal_size-1.0.0.dist-info
bleach
bleach-2.1.3.dist-info
concurrent
configparser-3.5.0.dist-info
configparser-3.5.0-nspkg.pth
configparser.py
configparser.pyc
dateutil
decorator-4.3.0.dist-info
decorator.py
decorator.pyc
easy-install.pth
easy_install.py
easy_install.pyc
entrypoints-0.2.3.dist-info
entrypoints.py
entrypoints.pyc
enum
enum34-1.1.6.dist-info
functools32
functools32-3.2.3.post2.dist-info
futures-3.2.0.dist-info
googleapiclient
google_api_python_client-1.6.5.dist-info
html5lib
html5lib-1.0.1.dist-info
httplib2
httplib2-0.10.3.dist-info
ipykernel
ipykernel-4.8.2.dist-info
ipykernel_launcher.py
ipykernel_launcher.pyc
IPython
ipython-5.7.0.dist-info
ipython_genutils
ipython_genutils-0.2.0.dist-info
ipywidgets
ipywidgets-7.2.1.dist-info
jinja2
Jinja2-2.10.dist-info
jsonschema
jsonschema-2.6.0.dist-info
jupyter-1.0.0.dist-info
jupyter_client
jupyter_client-5.2.3.dist-info
jupyter_console
jupyter_console-5.2.0.dist-info
jupyter_core
jupyter_core-4.4.0.dist-info
jupyter.py
jupyter.pyc
markupsafe
MarkupSafe-1.0.dist-info
mistune-0.8.3.dist-info
mistune.py
mistune.pyc
mpop-1.5.1-py2.7.egg
nbconvert
nbconvert-5.3.1.dist-info
nbformat
nbformat-4.4.0.dist-info
notebook
notebook-5.5.0.dist-info
oauth2client
oauth2client-4.1.2.dist-info
pandocfilters-1.4.2.dist-info
pandocfilters.py
pandocfilters.pyc
pathlib2
pathlib2-2.3.2.dist-info
pexpect
pexpect-4.6.0.dist-info
pickleshare-0.7.4.dist-info
pickleshare.py
pickleshare.pyc
pkg_resources
prompt_toolkit
prompt_toolkit-1.0.15.dist-info
ptyprocess
ptyprocess-0.5.2.dist-info
pyasn1
pyasn1-0.4.2.dist-info
pyasn1_modules
pyasn1_modules-0.2.1.dist-info
pydrive
PyDrive-1.3.1.dist-info
pygments
Pygments-2.2.0.dist-info
python_dateutil-2.7.3.dist-info
PyYAML-3.12.dist-info
pyzmq-17.0.0.dist-info
qtconsole
qtconsole-4.3.1.dist-info
rope
rope-0.10.7.dist-info
rsa
rsa-3.4.2.dist-info
scandir-1.7.dist-info
scandir.py
scandir.pyc
_scandir.so
send2trash
Send2Trash-1.5.0.dist-info
setuptools
setuptools-39.2.0.dist-info
setuptools.pth
shutil_backports
simplegeneric-0.8.1.dist-info
simplegeneric.py
simplegeneric.pyc
singledispatch-3.4.0.3.dist-info
singledispatch_helpers.py
singledispatch_helpers.pyc
singledispatch.py
singledispatch.pyc
six-1.11.0.dist-info
six.py
six.pyc
terminado
terminado-0.8.1.dist-info
testpath
testpath-0.3.1.dist-info
tornado
tornado-5.0.2.dist-info
traitlets
traitlets-4.3.2.dist-info
uritemplate
uritemplate-3.0.0.dist-info
wcwidth
wcwidth-0.1.7.dist-info
webencodings
webencodings-0.5.1.dist-info
widgetsnbextension
widgetsnbextension-3.2.1.dist-info
yaml
zmq
```


> NOTE: Debian is not one of our supported platforms so there is no guarantee that Polar2Grid will work on your system, but with a little bit of work it may be possible.

Some days ago was working in the same system. But today I tried it again and got the error

**Comment by kokkytos** [comment]
> > ```
> > from pykdtree.kdtree import KDTree`
> > ```
> 
> What's up with that trailing backtick? I don't see it in the [pyresample src](https://github.com/pytroll/pyresample/blob/master/pyresample/kd_tree.py#L29).

Sorry, I did it by mistake when I marked the text as code here.

**Comment by djhoese** [comment]
Did you actually do the `source` command first? The error message shows `/usr/bin/python` which is not the python that should be used.

By the way, my guess is that you installed packages using `pip install --user` when playing with pytroll packages (satpy, mpop, pyresample perhaps) and that installed packages in to `~/.local` which is causing issues. The `-s` passed to python is supposed to tell python *not* to look at `~/.local` for anything.

**Comment by kokkytos** [comment]
Sorry I didn't but after doing `source` 
`python -s -m polar2grid.glue -vv viirs_sdr gtiff -f 001/*.h5` is working!
```

INFO     : Initializing reader...
INFO     : Initializing remapping...
INFO     : Initializing backend...
INFO     : Initializing compositor objects...
INFO     : Extracting swaths from data files available...
WARNING  : Missing proper data files to create product: i05
WARNING  : Missing proper data files to create product: ifog
WARNING  : Missing proper data files to create product: m11
WARNING  : Missing proper data files to create product: i03
WARNING  : Missing proper data files to create product: m13
WARNING  : Missing proper data files to create product: i01
WARNING  : Missing proper data files to create product: m15
WARNING  : Missing proper data files to create product: m14
WARNING  : Missing proper data files to create product: i04
WARNING  : Missing proper data files to create product: m16
WARNING  : Missing proper data files to create product: m06
WARNING  : Missing proper data files to create product: m07
WARNING  : Missing proper data files to create product: m04
WARNING  : Missing proper data files to create product: m05
WARNING  : Missing proper data files to create product: m02
WARNING  : Missing proper data files to create product: m03
WARNING  : Missing proper data files to create product: m01
WARNING  : Missing proper data files to create product: m08
WARNING  : Missing proper data files to create product: m09
WARNING  : Missing proper data files to create product: i02
WARNING  : Missing proper data files to create product: m10
WARNING  : Missing proper data files to create product: m12
INFO     : Creating navigation product 'dnb_longitude'
INFO     : Creating navigation product 'dnb_latitude'
INFO     : Creating data product 'dnb'
INFO     : Creating data product 'dnb_solar_zenith_angle'
ERROR    : Could not extract data from file. Use '--no-tc' flag if terrain-corrected data is not available
ERROR    : Could not create raw product 'dnb_solar_zenith_angle'
INFO     : Creating data product 'dnb_lunar_zenith_angle'
ERROR    : Could not extract data from file. Use '--no-tc' flag if terrain-corrected data is not available
ERROR    : Could not create raw product 'dnb_lunar_zenith_angle'
INFO     : Creating secondary product 'dynamic_dnb'
ERROR    : Could not create product (unexpected error): 'dynamic_dnb'
INFO     : Creating secondary product 'hncc_dnb'
ERROR    : Could not create product (unexpected error): 'hncc_dnb'
INFO     : Creating secondary product 'adaptive_dnb'
ERROR    : Could not create product (unexpected error): 'adaptive_dnb'
ERROR    : No products were returned by the frontend
ERROR    : Frontend data extraction failed (see log for details)

```
Indeed, first I test _polar2grid_ and was working. Then I install _satpy_ etc. And now _polar2grid_ is broken.

**Comment by djhoese** [comment]
If `~/.local` was only being used for satpy/pytroll packages then I *highly* recommend deleting `~/.local` and using conda (with the conda-forge channel) to install the packages. Of course this all depends on what you're comfortable with and how much you want to have to work around the polar2grid stuff. You could edit the `polar2grid.sh` script to add the `-s` flag if you want.

Also your above output shows polar2grid failed later on. It looks like you didn't provide terrain corrected data files to P2G. If you use `--no-tc` or provide the GITCO/GMTCO files then things should work.

**Comment by kokkytos** [comment]
Can I delete` ~/.local`. It contains a lot of folders (bin,  etc,  lib, share) and files and maybe it will break other things... I will check conda. 
I provided only GDNBO for DNB. Should I provide GITCO/GMTCO for DNB? Aren't they for I and M bands?

**Comment by djhoese** [comment]
To be save you could try moving it to a different name and try the `polar2grid.sh` script again. You are right GITCO/GMTCO shouldn't be needed for DNB. Is this old DNB data? Newer DNB files (within the last 4 years probably) contain terrain corrected data inside the GDNBO files.

**Comment by kokkytos** [comment]
The data are for 2018 so it's ok.
Thank you for your time!
