### ISSUE TITLE
latitude/longitude gtiff images cannot be created using viirs_edr_active_fires reader with polar2grid 2.3.0a2

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#204]
When listing products for the viirs_edr_active_fires reader, latitude and longitude are offered as options for both the IMG and MOD resolution .nc files.  But if you try to create gtiff files, the processing fails with a log file entry of:

satpy.readers.yaml_reader : _load_dataset_area : No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=())

I do not think it necessary to support these anyway, but someone will try to create them if it is listed as an option.

**Comment by djhoese** [comment]
Can you verify that this is an error (not a warning) and is the reason for failed processing? This message is typically shown as a warning but should not cause a failure.

**Comment by kathys** [comment]
It fails.  If you provide it with a list of other products, none are created.

polar2grid.sh viirs_edr_active_fires gtiff -p T13 latitude -f ../fires/AFMOD*.nc

Last part of Log File:

[2019-08-20 16:55:51,158] : PID   8582 : DEBUG    : satpy.readers.yaml_reader : _load_dataset_area : No coordinates found for DatasetID(name='longitude', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=())
[2019-08-20 16:55:51,297] : PID   8582 : DEBUG    : satpy.readers.yaml_reader : _load_dataset_area : No coordinates found for DatasetID(name='latitude', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=())
[2019-08-20 16:55:51,603] : PID   8582 : DEBUG    : viirs_edr_active_fires2gtiff : main : Frontend data extraction exception:
Traceback (most recent call last):
  File "/data4/viirs/test/p2g/v2.3/polar2grid_v_2_3/lib/python3.7/site-packages/polar2grid/glue_legacy.py", line 334, in main
    scene = convert_satpy_to_p2g_swath(f, scene)
  File "/data4/viirs/test/p2g/v2.3/polar2grid_v_2_3/lib/python3.7/site-packages/polar2grid/readers/__init__.py", line 302, in convert_satpy_to_p2g_swath
    a = ds.attrs['area']
KeyError: 'area'
[2019-08-20 16:55:51,604] : PID   8582 : ERROR    : viirs_edr_active_fires2gtiff : main : Frontend data extraction failed (see log for details)

**Comment by djhoese** [comment]
Ok, so you are saying we shouldn't show `latitude` and `longitude` as possible loadable datasets at all, right?

FYI the error I was looking for was:

```
packages/polar2grid/readers/__init__.py", line 302, in convert_satpy_to_p2g_swath
a = ds.attrs['area']
KeyError: 'area'
```

Thanks for the extra info.

**Comment by kathys** [comment]
Unless you can think of a use case for them, I say you just remove them from the product list.

**Comment by djhoese** [comment]
This was changed a while ago. @kathys can you verify that `longitude` and `latitude` datasets from the viirs_edr_active_fires reader are not listed in the latest tarball you have?

**Comment by djhoese** [comment]
Duh, this is simple enough for me to test. This should be fixed.
