### ISSUE TITLE
HDF5 writer is not python 3 compatible

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#215]
The new mersi2_l1b writer is not functional.

Test data:  bumi:/data/users/kathys/test_data/fy3d_mersi/formitch/data

Log file: bumi:/data/users/kathys/test_data/fy3d_mersi/formitch/hdf5/mersi2_l1b2hdf5_20190916_173251.log

Invocation: /data/users/kathys/polar2grid_v_2_3/lib/python3.7/site-packages/polar2grid/glue_legacy.py mersi2_l1b hdf5 -p 1 2 3 4 6 7 20 25 -f ../data/tf2019259173245.FY3D-X_MERSI_0250M_L1B.HDF ../data/tf2019259173245.FY3D-X_MERSI_1000M_L1B.HDF ../data/tf2019259173245.FY3D-X_MERSI_GEO1K_L1B.HDF ../data/tf2019259173245.FY3D-X_MERSI_GEOQK_L1B.HDF -vv

End of log message:  

```
[2019-10-16 18:55:01,595] : PID 192360 : INFO     : mersi2_l1b2hdf5 : main : Creating output from data mapped to grid wgs84_fit

[2019-10-16 18:55:01,596] : PID 192360 : ERROR    : mersi2_l1b2hdf5 : exc_handler : Unexpected error. Enable debug messages (-vvv) or see log file for details.

[2019-10-16 18:55:01,596] : PID 192360 : DEBUG    : mersi2_l1b2hdf5 : exc_handler : Unexpected error exception:

Traceback (most recent call last):

  File "/data/users/kathys/polar2grid_v_2_3/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/data/users/kathys/polar2grid_v_2_3/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/data/users/kathys/polar2grid_v_2_3/lib/python3.7/site-packages/polar2grid/glue_legacy.py", line 504, in <module>

    sys.exit(main())

  File "/data/users/kathys/polar2grid_v_2_3/lib/python3.7/site-packages/polar2grid/glue_legacy.py", line 487, in main

    backend.create_output_from_scene(gridded_scene, **args.subgroup_args["Backend Output Creation"])

  File "/data/users/kathys/polar2grid_v_2_3/lib/python3.7/site-packages/polar2grid/hdf5_backend.py", line 95, in create_output_from_scene

    output_filename = self.determine_output_filename(gridded_scene, output_pattern=kwargs["output_pattern"])

  File "/data/users/kathys/polar2grid_v_2_3/lib/python3.7/site-packages/polar2grid/hdf5_backend.py", line 70, in determine_output_filename

    k = gridded_scene.keys()[0]

TypeError: 'dict_keys' object is not subscriptable
```

**Comment by djhoese** [comment]
As mentioned in person, this is the HDF5 writer in general and is not specific to the MERSI-2 reader. In the large migration to python 3 it seems I missed this one piece of code. The rest of the HDF5 writer seems fine. Closed with #217.
