### ISSUE TITLE
polar2grid-swbundle-2.3.0b4.tar.gz fails on Flood Area of Interest files

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#243]
The Flood software allows an end user to create flood detection VIIRS products of smaller scenes that a user defines by lat/lon boundaries.  I do not think there is any difference in these files from a full swath file besides an added file name segment.  However `polar2grid.sh viirs_edr_flood gtiff` fails.  

"Full swath CSPP VIIRS Flood file name:  WATER_VIIRS_Prj_SVI_j01_d20190822_t1731511_e1743123_b09114_cspp_dev_18341_13093_01.hdf"

"Area of Interest file name:  WATER_VIIRS_Prj_SVI_j01_d20190822_t1731511_e1743123_b09114_cspp_dev_001_1187_1187_01.hdf "

Note the "001".  There can be more than 1, so 1-100 is valid.

"[2019-12-02 23:29:21,314] : PID  34862 : INFO     : viirs_edr_flood2gtiff : main : Initializing compositor objects...
[2019-12-02 23:29:21,314] : PID  34862 : INFO     : viirs_edr_flood2gtiff : main : Extracting swaths from data files available...
[2019-12-02 23:29:21,315] : PID  34862 : DEBUG    : polar2grid.readers : create_scene : Loading scene data...
[2019-12-02 23:29:21,329] : PID  34862 : DEBUG    : viirs_edr_flood2gtiff : main : Frontend data extraction exception:
Traceback (most recent call last):
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/polar2grid/glue_legacy.py", line 326, in main
    scene = f.create_scene(**args.subgroup_args["Frontend Swath Extraction"])
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/polar2grid/readers/__init__.py", line 440, in create_scene
    self.scene.load(products, generate=self.GENERATE_COMPOSITES, **kwargs)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/satpy/scene.py", line 973, in load
    self.read(**kwargs)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/satpy/scene.py", line 882, in read
    return self._read_datasets(nodes, **kwargs)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/satpy/scene.py", line 723, in _read_datasets
    new_datasets = reader_instance.load(ds_ids, **kwargs)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 843, in load
    ds = self._load_dataset_with_area(dsid, coords)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 759, in _load_dataset_with_area
    ds = add_crs_xy_coords(ds, area)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/satpy/resample.py", line 302, in add_crs_xy_coords
    data_arr = add_xy_coords(data_arr, area, crs=crs)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/satpy/resample.py", line 247, in add_xy_coords
    return data_arr.assign_coords(y=y, x=x)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/xarray/core/common.py", line 452, in assign_coords
    data.coords.update(results)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/xarray/core/coordinates.py", line 118, in update
    self._update_coords(coords, indexes)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/xarray/core/coordinates.py", line 291, in _update_coords
    dims = calculate_dimensions(coords_plus_data)
  File "/home/dbproc/dbvm/apps/polar2grid/polar2grid/lib/python3.7/site-packages/xarray/core/dataset.py", line 186, in calculate_dimensions
    % (dim, size, k, dims[dim], last_used[dim])
ValueError: conflicting sizes for dimension 'x': length 1187 on <this-array> and length 11187 on 'x'
[2019-12-02 23:29:21,331] : PID  34862 : ERROR    : viirs_edr_flood2gtiff : main : Frontend data extraction failed (see log for details)"

**Comment by kathys** [comment]
I put examples here - bumi:/data/users/kathys/test_data/viirs_flood

The log files is in the /gtiff directory.

**Comment by djhoese** [comment]
Ok I figured it out. The satpy reader is trying out two different file patterns to see if it knows how to read this file; one for the full swath then one for the aoi region. The problem is that the full swath file pattern is matching the file provided for the AOI case where it thinks "001_1187" is the number of columns (001_1187 -> 11187). The reader is using this information from the filename to create the definition of the grid for this data. When it gets to loading the data it sees 1187 columns but previously thought it would get 11187.

Good news is this is a simple fix. I'll work on it tomorrow.
