### ISSUE TITLE
P2G v3.0 default wgs84 projection output fails with MODIS L1B input

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#427]
Setting up my test direct broadcast processing system for MODIS using P2G v3.0 and it fails to produce WGS84 default projection dynamic GeoTIFF output files.  The log files says

WARNING  : Resampling found nan% of the output grid covered. Will skip producing this product: 35

It says that for all of the products.  Using a predefined grid mostly works.  

One bumi example log file can be found here:
bumi:/data/users/kathys/version_3_0_timing/cutouts/full_pass_terra_v3_0_tiff

Data location  
bumi:/data/users/kathys/version_3_0_timing/cutouts/terra_input

Implementation:  
$POLAR2GRID_HOME/bin/polar2grid.sh -r modis_l1b -w geotiff --num-workers 4 --fill-value 0 -f /data/users/kathys/version_3_0_timing/cutouts/terra_input

**Comment by kathys** [comment]
Polar2Grid version **polar2grid-swbundle-20220322-204235** still will not create products using the default dynamic grids.  Same implementation as stated above.  New log file is _bumi:/data/users/kathys/version_3_0_timing/cutouts/full_pass_terra_v3_0_tiff_


Traceback (most recent call last):
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/polar2grid/glue.py", line 972, in <module>
    sys.exit(main())
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/polar2grid/glue.py", line 889, in main
    return _run_processing(
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/polar2grid/glue.py", line 952, in _run_processing
    to_save = _save_scenes(scenes_to_save, reader_info, writer_args)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/polar2grid/glue.py", line 801, in _save_scenes
    to_save = write_scene(
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/polar2grid/glue.py", line 188, in write_scene
    res = scn.save_datasets(writer=writer_name, compute=False, datasets=datasets, **wargs)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/satpy/scene.py", line 1144, in save_datasets
    return writer.save_datasets(dataarrays, compute=compute, **save_kwargs)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/satpy/writers/__init__.py", line 688, in save_datasets
    results.append(self.save_dataset(ds, compute=False, **kwargs))
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/satpy/writers/__init__.py", line 814, in save_dataset
    return self.save_image(img, filename=filename, compute=compute, fill_value=fill_value, **kwargs)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/satpy/writers/geotiff.py", line 246, in save_image
    filename = filename or self.get_filename(**img.data.attrs)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/satpy/writers/__init__.py", line 649, in get_filename
    output_filename = self.filename_parser.compose(kwargs)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/trollsift/parser.py", line 57, in compose
    return compose(fmt=self.fmt, keyvals=keyvals, allow_partial=allow_partial)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/trollsift/parser.py", line 475, in compose
    return _strict_compose(fmt=fmt, keyvals=keyvals)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/site-packages/trollsift/parser.py", line 672, in _strict_compose
    return formatter.format(fmt, **keyvals)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/string.py", line 161, in format
    return self.vformat(format_string, args, kwargs)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/string.py", line 165, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/string.py", line 205, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/string.py", line 270, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/data/users/kathys/polar2grid-swbundle-20220322-204235/libexec/python_runtime/lib/python3.10/string.py", line 227, in get_value
    return kwargs[key]
KeyError: 'platform_name'

**Comment by kathys** [comment]
This turned out to be a bigger problem.  The same problem appears with VIIRS.  When trying to produce all default geotiff products, the image creation fails with the same error message.

File "/data3/users/kathys/new_p2g_test/dbvm/apps/polar2grid/polar2grid/libexec/python_runtime/lib/python3.10/string.py", line 227, in get_value
    return kwargs[key]
KeyError: 'platform_name'

**Comment by djhoese** [comment]
Ok, so this looks like it is a change in newer xarray that is revealing a bug in Satpy. The main issue seems to be with the `fog` (`ifog` in VIIRS) where the scaling/enhancement code is accidentally removing all the metadata. When this data is then passed to the writer and it tries to format an output filename it just chokes because no metadata exists. Working on a fix.
